---
title: In-utero and infancy factors and thyroid cancer risk in adult women in the Sister Study cohort
subtitle: "Main tables and figures"
toc: true
number-sections: true
format:
  html:
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
execute: 
  warning: false
  output: true
editor: visual
---

```{r}
###Necessary R library and data loading
library(here)
library(tidyverse)
library(gtsummary)
library(survival)
library(cmprsk)
library(broom)
library(broom.helpers)
library(tidymodels)


earlylife_popu <-
  read.csv(
    here::here("data/ss_earlylife_popu.csv"),
    header = TRUE,
    stringsAsFactors = TRUE,
    fileEncoding = "latin1"
  )

```

```{r}
#List of exposures of interest and covariates
#Create variable list to avoir repetition in the code

#Covariates to adjust in Cox models
covariates_label = list(
  "ses_race"~"Race",
  "an_bmi_cat"~"BMI",
  "smok_status"~"Smoking status",
  "ses_edu_level"~"Educational level",
  "ses_income"~"Household income",
  "illness_thyroid_all"~"Benign thyroid disease"
)
covariates = substr(covariates_label, 2, unlist(gregexpr("~", covariates_label)) - 3)

# add_covariates_label = list(
#   "rep_meno_age_cat"~"Age at menopause"
#   "ph_MET_wk_current_cat"~"Physical activity (MET hours/week)"  ,
#   "ph_MET_wk_current_cont"~"Physical activity (MET hours/week)"  ,
#   "PH_CurrentTotMETHrsPerWeek_CDC"~"Physical activity (MET hours/week)",
#   "ph_hrs_wk_current_cont"~"Physical activity (total hours/week)"    ,
#   "ses_marital_status"~"Marital status"
#   "sm_pack_yr_cat"~"Smoking (pack/year)"            ,
#   "sm_pack_yr_cont"~"Smoking (pack/year)"
#   "sm_yr_smok_cat"~"Years of smoking"    ,
#   "sm_yr_smok_cont"~"Years of smoking"   ,
#   "sm_ETS_ever"~"Ever secondhand smoking"       ,
#   "sm_ETS_total_yr_cat"~"Total years of secondhand smoking"    ,
#   "sm_ETS_total_yr_cont"~"Total years of secondhand smoking"
# )
# add_covariates = substr(add_covariates_label, 2, unlist(gregexpr("~", add_covariates_label)) - 3)

#In-utero and infancy factors
var_label_utero = list(
  "ui_diab_all_mother"~"Pre-pregnancy or gestational diabetes",
  "ui_hypertension_all"~"Gestational hypertension or pre-eclampsia",
  "ui_epilepsy_prior"~"Epilepsy",
  "ui_vomit"~"Morning sickness with vomiting",
  "ui_DES"~"DES use",
  "ui_mother_smok"~"Smoking during pregnancy",
  "ui_hh_smok"~"Anyone smoking in the household during pregnancy",
  "ui_mother_age_cat"~"Age at delivery",
  "ui_mother_age_cont"~"Age at delivery (year, continuous)",
  "ui_diab_father"~"Diabetes",
  "ui_father_smok"~"Smoking during 3 months before conception",
  "ui_father_age_cat"~"Age at delivery",
  "ui_father_age_cont"~"Age at delivery (year, continuous)",
  "ui_birth_weight_cat"~"Birthweight",
  "ui_birth_weight_cont"~"Birthweight (continuous)",
  "ui_maternal_1st_born"~"First born",
  "ui_preg_order_cat"~"Order of birth",
  "ui_preg_order_cont"~"Order of birth (continuous)",
  "ui_preg_last_cat"~"Time since the last birth",
  "ui_preg_last_cont"~"Time since the last birth (year, continuous)",
  "ui_multiple_birth"~"Multiple birth",
  "ui_early_gest"~"Gestational age at birth",
  "ui_breastfed"~"Ever breastfed",
  "ui_soy"~"Ever fed soy formula"
)
var_name_utero = substr(var_label_utero, 2, unlist(gregexpr("~", var_label_utero)) - 3)

#Childhood factors
var_label_childhood = list(
"rep_br_dev_age_cat"~"Age at breast development"  ,           
"rep_br_dev_age_cont"~"Age at breast development" ,         
"rep_age_menarche_cat"~"Age at menarche"   ,      
"rep_age_menarche_cont"~"Age at menarche"   ,     
"rep_bc_ever"~"Ever used hormonal birth control" ,                 
"rep_bc_ado"~"Hormonal birth control under age 20"  ,                 
"rep_bc_ado_dur_cat"~"Hormonal birth control duration under age 20",            
"rep_bc_ado_dur_cont"~"Hormonal birth control duration under age 20"   ,        
"rep_bc_min_age_cat"~"Start age for hormonal birth control" ,           
"rep_bc_min_age_cont"~"Start age for hormonal birth control"    ,      
# "rep_proges_ado"~"Progestin-only birth control under age 20"     ,           
# "rep_proges_ado_dur_cat"~"Progestin-only birth control duration under age 20" ,       
# "rep_proges_ado_dur_cont"~"Progestin-only birth control duration under age 20"    ,   
# "rep_proges_min_age_cat"~"Start age for progestin-only birth control"    ,   
# "rep_proges_min_age_cont"~"Start age for progestin-only birth control"   ,    
# "rep_combined_ado"~"Combined hormonal birth control under age 20" ,             
# "rep_combined_ado_dur_cont"~"Combined hormonal birth control duration under age 20" ,    
# "rep_combined_ado_dur_cat"~"Combined hormonal birth control duration under age 20"   ,   
# "rep_combined_min_age_cont"~"Start age for combined hormonal birth control"   ,  
# "rep_combined_min_age_cat"~"Start age for combined hormonal birth control"  ,   
# "rep_bc_ado_type"~"Types of hormonal birth control under age 20"      ,         
# "rep_bc_ingredient"~"Ingredient of hormonal birth control under age 20"   ,          
"an_weight_age10"~"Weight at age 10 vs. peers"    ,     
"an_height_age10"~"Height at age 10 vs. peers"    ,           
"an_weight_teen"~"Teenage weight vs. peers"      ,          
"an_age_tallest"~"Age reached full adult height"      ,          
"ph_hrs_wk_child_cat"~"Physical activity before age 13 (total hours/week)"   ,        
"ph_hrs_wk_child_cont"~"Physical activity before age 13 (total hours/week)"   ,       
"ph_MET_wk_child_cat"~"Physical activity before age 13 (MET hours/week)"  ,         
"ph_MET_wk_child_cont"~"Physical activity before age 13 (MET hours/week)"   ,       
"ph_hrs_wk_teen_cat"~"Physical activity from 13 and 19 (total hours/week)"  ,    
"ph_hrs_wk_teen_cont"~"Physical activity from 13 and 19 (total hours/week)"  ,   
"ph_MET_wk_teen_cat"~"Physical activity between the age of 13 and 19 (MET hours/week)"    ,        
"ph_MET_wk_teen_cont"~"Physical activity between the age of 13 and 19 (MET hours/week)"   ,        
"ph_MET_wk_before20_cat"~"Physical activity before age 20 (MET hours/week)"      ,  
"ph_MET_wk_before20_cont"~"Physical activity before age 20 (MET hours/week)" ,
"ph_hrs_wk_before20_cat"~"Physical activity before age 20 (total hours/week)"    ,    
"ph_hrs_wk_before20_cont"~"Physical activity before age 20 (total hours/week)"    ,   
"alc_drinks_before20_cat"~"Alcohol consumption under 20 (drinks/year)"     ,     
"alc_drinks_before20_cont"~"Alcohol consumption under 20 (drinks/year)"     ,    
"alc_binge_time_519_cat"~"Times per year drank 4+ drinks under 20"     ,   
"alc_binge_time_519_cont"~"Times per year drank 4+ drinks under 20"     , 
"alc_age_start_reg_cat"~"Age started drinking regularly"         ,
"alc_age_start_reg_cont"~"Age started drinking regularly"        ,
"sm_age_start_smok_cat"~"Age started smoking"   ,      
"sm_age_start_smok_cont"~"Age started smoking"  ,      
"sm_age_stop_smok_cat"~"Age stopped smoking"    ,      
"sm_age_stop_smok_cont"~"Age stopped smoking"   ,      
"sm_ETS_before18"~"Secondhand smoking under 18"     ,             
"sm_ETS_before18_yr_cat"~"Total years of secondhand smoking under 18"   ,        
"sm_ETS_before18_yr_cont"~"Total years of secondhand smoking under 18"  ,        
"smok_before20"~"Smoking before 20"       ,          
"sm_pack_yr_1019_cat"~"Smoking from 10 and 19 (Pack-years)"    , 
"sm_pack_yr_1019_cont"~"Smoking from 10 and 19 (Pack-years)"  ,        
"sm_pack_yr_before20_cat"~"Smoking before 20 (Pack-years)"  ,       
"sm_pack_yr_before20_cont"~"Smoking before 20 (Pack-years)"  ,       
"sm_yr_smok_1019_cat"~"Total years of smoking from 10 to 19"    ,       
"sm_yr_smok_1019_cont"~"Total years of smoking from 10 to 19"   ,       
"sm_yr_smok_before20_cat"~"Total years of smoking before 20"     ,     
"sm_yr_smok_before20_cont"~"Total years of smoking before 20"   ,
"ses_income_child"~"Family income while growing up"         ,     
"ses_hunger_child"~"Ever not having enough to eat during childhood"          ,    
"ses_edu_level_child"~"Highest household education level at age 13"     
)
var_name_childhood = substr(var_label_childhood, 2, unlist(gregexpr("~", var_label_childhood)) - 3)

```

```{r}
#Functions to generate tables
#Create functions that I'll use in the codes

#1. Function for descriptive info
descript_table = function(var_name, var_label)
{
  Descriptive_table = earlylife_popu[,-1]   |>
    tbl_summary(
      include = var_name,
      type = all_continuous() ~ "continuous",
      statistic = list(
        all_continuous()
        ~ c("{median} ({p25}, {p75})"),
        all_categorical() ~ "{n} ({p}%)"
      ),
      label = var_label,
      digits = all_continuous() ~ 1,
      missing = "ifany"
    )  |>
    remove_row_type(variables = ses_race,
                    type = "level",
                    level_value = "Unknown")  |>
    remove_row_type(
      variables = ses_race_detail,
      type = "level",
      level_value = c("1) Non-Hispanic White",
                      "2) Non-Hispanic Black",
                      "3) Hispanic")
    )  |>
    remove_row_type(variables = ses_race_detail,
                    type = "header")
  return(Descriptive_table)
}

#2. Function for cox models
cox_model = function(var_name, var_label)
{
  results_cox_function = c(var_name) |>
    reformulate(response = surv) |>
    coxph(method = "breslow", data = earlylife_popu)  |>
    tbl_regression(
      exponentiate = TRUE,
      conf.int = TRUE,
      conf.level = 0.95,
      add_estimate_to_reference_rows = TRUE,
      label = var_label,
      include = var_name[!(var_name %in% covariates)]
    )   |>
    modify_column_hide(p.value) |>
    modify_table_styling(
      columns = c(estimate, ci),
      rows = p.value < 0.05,
      text_format = "bold"
    ) |>
    modify_header(n_event ~ "**Number of events**",
                  exposure ~ "**Person-years**",
                  estimate ~ "**HR**") |>
    modify_table_body( ~ .x %>% dplyr::relocate(exposure, .before = estimate))
  return(results_cox_function)
  rm(results_cox_function)
}


```

## **Table 1 Association between in-utero and infancy factors and thyroid cancer incidence**

```{r}
#| label: tbl-stats
#| tbl-cap: "Association between in-utero and infancy factors and thyroid cancer incidence"

surv = "Surv(ident_ageexact_bl, ident_EOF, ident_DTC)"

####Loop over in utero and infancy factors in cox models, both univariate and multivariate analyses
for (i in c(1:24))
{
  temp_dat_univariate = cox_model(var_name = var_name_utero[i], var_label = var_label_utero[i])
  
  temp_dat_multivariate = cox_model(var_name = c(var_name_utero[i], covariates),
                                    var_label = var_label_utero[i])
  
  if (i == 1) {
    univariate = temp_dat_univariate
    multivariate=temp_dat_multivariate
  }
  else     {
    univariate = tbl_stack(list(univariate, temp_dat_univariate))
    multivariate = tbl_stack(list(univariate, temp_dat_multivariate))
  }
}

#assemble descriptive table and cox models' results
descript_utero = descript_table(var_name = var_name_utero, 
                                var_label = var_label_utero)
cox_utero = tbl_merge(
  tbls = list(descript_utero, univariate, multivariate),
  tab_spanner = c("**N (%)**",
                  "**Univariate models**",
                  "**Multivariate models**")) |> 
#polish the table
  modify_footnote(
    abbreviation = TRUE,
    `estimate_2` ~ "Multivariate models were adjusted for race/ethnicity, baseline BMI, baseline thyroid benign disease, household income, smoking status, and educational level"
  ) |>
  modify_table_body(
    ~ .x  |>
      dplyr::add_row(
        label = "Maternal pregnancy characteristics",
        .before = grep("ui_diab_all_mother", cox_utero$table_body$variable)
      )  |>
      dplyr::add_row(
        label = "Paternal pregnancy characteristics",
        .before = grep("ui_diab_father", cox_utero$table_body$variable) + 1
      )  |>
      dplyr::add_row(
        label = "Birth and infancy characteristics",
        .before = grep("ui_birth_weight_cat", cox_utero$table_body$variable) + 2
      )
  ) |>
  modify_table_styling(
    column = "label",
    rows = cox_utero$table_body$label %in% c(
      "Participant characteristics at baseline",
      "Maternal pregnancy characteristics",
      "Paternal pregnancy characteristics",
      "Birth and infancy characteristics"
    ),
    text_format = "bold"
  )          

#return the table 
cox_utero
rm(temp_dat_multivariate,temp_dat_univariate,descript_utero, univariate, multivariate)

```

## **Table 2 Association between childhood factors and thyroid cancer incidence**

```{r}
#| label: tbl-stats
#| tbl-cap: "Association between childhood factors and thyroid cancer incidence"

surv = "Surv(ident_ageexact_bl, ident_EOF, ident_DTC)"
temp_dat=null_data()

####Loop over in childhood factors in cox models

```

```{r}
quarto::quarto_render("early_life.qmd")
```
